JVC=javac

FILE1=Player
FILE2=Ball
FILE3=Score

default: all

all: $(FILE1).java $(FILE2).java $(FILE3).java
	$(JVC) $(FILE1).java
	$(JVC) $(FILE2).java
	$(JVC) $(FILE3).java

clean:
	rm $(FILE1).class
	rm $(FILE2).class
	rm $(FILE3).class
